* Academic

** Education

   - 2014–2018 :: Master studies in Philosophy, University of Potsdam,
     Germany (first year at the Technical University of Berlin) [Final
     grade 1,3]\\
     Master thesis: /Creativity Between Nature and Culture/
     [Grade 1,0]
   - 2007–2011 :: Bachelor studies (double major) in Philosophy
     (/summa cum laude/) and Music theory, University of Haifa, Israel
     (English Language and Literature during the first year) [Final grade 95%]

** Teaching

   - Winter semester 2016/17 :: Tutorial seminar “Teleology”,
     Department of Philosophy, University of Potsdam, Germany (as part
     of the master studies).

** Conferences and Others

   - July 2016 :: Aggregate States of Knowledge: An Experimental
     Workshop Observing the Poietic Processes of Understanding. With
     Prof. Karen van den Berg and Johanna Dehio, IKKM, Bauhaus
     University, Weimar.

** Honors and Awards

   - 2011 :: Dean's List, Faculty of Humanities, University of Haifa.
   - 2010 :: Prof. Yaakov Kogan Prize, Department of Philosophy,
     University of Haifa.

** Scholarships

   - 2011 :: DAAD Scholarship for a Berlin summer school in German.

