---
papersize: a4
pagestyle: empty
fontsize: 12pt
mainfont: Linux Libertine
mainfontoptions:
  - Scale=1
sansfont: Linux Biolinum
sansfontoptions:
  - Scale=1
geometry:
    - top=25mm
    - left=30mm
    - right=35mm
    - bottom=30mm
colorlinks: true
urlcolor: url-color
---
